spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true